In [1]:
def my_function():
    pass

In [2]:
def my_sq(x):
    return x ** 2

In [3]:
my_sq(4)

16

In [4]:
my_sq("hello")

TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

In [5]:
assert my_sq(4) == 16

In [6]:
assert my_sq(4) == 20

AssertionError: 

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame({
    "a": [10, 20, 30],
    "b": [20, 30, 40]
})

In [9]:
df

a   b
0  10  20
1  20  30
2  30  40

In [10]:
df["a"] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [11]:
type(df["a"])

pandas.core.series.Series

In [12]:
df["a"].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [13]:
def my_exp(x, e):
    return x ** e

In [14]:
my_exp(4, 2)

16

In [15]:
my_exp(2, 10)

1024

In [19]:
df["a"].apply(my_exp, e=10)

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [21]:
df["a"].apply(lambda val: my_exp(x=val, e=10))

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [22]:
df["a"].apply(lambda val: my_exp(x=10, e=val))

0                        10000000000
1              100000000000000000000
2    1000000000000000000000000000000
Name: a, dtype: object

In [23]:
def print_me(x):
    print(x)

In [24]:
print_me("daniel")

daniel


In [25]:
df["a"].apply(print_me)

10
20
30


0    None
1    None
2    None
Name: a, dtype: object

In [26]:
df

a   b
0  10  20
1  20  30
2  30  40

In [27]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [28]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [29]:
assert avg_3(0, 5, 10) == 5

In [30]:
df.apply(avg_3)

TypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'

In [31]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [32]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [33]:
df.apply(print_me, axis="columns")

a    10
b    20
Name: 0, dtype: int64
a    20
b    30
Name: 1, dtype: int64
a    30
b    40
Name: 2, dtype: int64


0    None
1    None
2    None
dtype: object

In [34]:
df

a   b
0  10  20
1  20  30
2  30  40

In [35]:
def avg_2(x, y):
    return (x + y) / 2

In [38]:
(df["a"] + df["b"]) / 2

0    15.0
1    25.0
2    35.0
dtype: float64

In [39]:
avg_2(df["a"], df["b"])

0    15.0
1    25.0
2    35.0
dtype: float64

In [42]:
import numpy as np

def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    return (x + y) / 2

In [45]:
avg_2_mod(20, 10)

nan

In [46]:
avg_2_mod(0, 10)

5.0

In [43]:
avg_2_mod(df["a"], df["b"])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [44]:
df["a"] == 20

0    False
1     True
2    False
Name: a, dtype: bool

In [56]:
import numpy as np
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    return (x + y) / 2

avg_2_mod_np = np.vectorize(avg_2_mod)

In [57]:
avg_2_mod_np(df["a"], df["b"])

array([15., nan, 35.])

In [58]:
@np.vectorize
def avg_2_mod_np(x, y):
    if (x == 20):
        return np.NaN
    return (x + y) / 2

In [59]:
avg_2_mod_np(df["a"], df["b"])

array([15., nan, 35.])

In [52]:
import numba

In [60]:
@numba.vectorize
def avg_2_mod_numba(x, y):
    if (x == 20):
        return np.NaN
    return (x + y) / 2

In [61]:
avg_2_mod_numba(df["a"], df["b"])

ValueError: Cannot determine Numba type of <class 'pandas.core.series.Series'>

In [63]:
type(df["a"])

pandas.core.series.Series

In [66]:
type(df["a"].values)

numpy.ndarray

In [67]:
df["a"].values

array([10, 20, 30], dtype=int64)

In [68]:
avg_2_mod_numba(df["a"].values, df["b"].values)

array([15., nan, 35.])

In [69]:
%%timeit
avg_2(df["a"], df["b"])

266 µs ± 13.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [70]:
%%timeit
avg_2_mod_np(df["a"], df["b"])

72.8 µs ± 3.89 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [71]:
%%timeit
avg_2_mod_numba(df["a"].values, df["b"].values)

12.4 µs ± 334 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [73]:
# exercise use the get_pop column on the rate column to assign a new column called population
tbl3 = pd.read_csv("data/table3.csv")
tbl3

country  year               rate
0  Afghanistan  1999       745/19987071
1  Afghanistan  2000      2666/20595360
2       Brazil  1999    37737/172006362
3       Brazil  2000    80488/174504898
4        China  1999  212258/1272915272
5        China  2000  213766/1280428583

In [76]:
def get_pop(rate):
    return int(rate.split("/")[1])

In [77]:
get_pop("745/19987071")

19987071

In [80]:
tbl3["population"] = tbl3["rate"].apply(get_pop)

In [81]:
tbl3

country  year               rate  population
0  Afghanistan  1999       745/19987071    19987071
1  Afghanistan  2000      2666/20595360    20595360
2       Brazil  1999    37737/172006362   172006362
3       Brazil  2000    80488/174504898   174504898
4        China  1999  212258/1272915272  1272915272
5        China  2000  213766/1280428583  1280428583

In [82]:
@np.vectorize
def get_pop_v(rate):
    return int(rate.split("/")[1])

In [84]:
tbl3["population_v"] = get_pop_v(tbl3["rate"])

In [85]:
tbl3

country  year               rate  population  population_v
0  Afghanistan  1999       745/19987071    19987071      19987071
1  Afghanistan  2000      2666/20595360    20595360      20595360
2       Brazil  1999    37737/172006362   172006362     172006362
3       Brazil  2000    80488/174504898   174504898     174504898
4        China  1999  212258/1272915272  1272915272    1272915272
5        China  2000  213766/1280428583  1280428583    1280428583